name: Master branch CI
on:
  workflow_dispatch:
  push:
    branches:
      - master

defaults:
  run:
    shell: bash

jobs:
  release_prod:
    runs-on: ubuntu-24.04
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12.3

      - name: Install dependencies
        run: |
          pip install pyinstaller
          pip install -r requirements.txt

      - name: Build binary using PyInstaller
        run: |
          pyinstaller validay.spec

      - name: Tag with next sematic version
        uses: pfaff-consulting/rod/.github/actions/tag@develop
        with:
          release_type: minor

      - name: Create GitHub RELEASE
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "${{ env.VERSION }}"
          name: "Release ${{ env.VERSION }}"
          files: dist/validay
